### ISSUE TITLE
onChange has error with this.setState

### ISSUE THREAD

**Issue by creatorkuang** [jakemmarsh/react-rocket-boilerplate#21]
this.setState not found, I founded that this refer to store object but not react.

**Comment by jakemmarsh** [comment]
Sorry, not entirely sure what you're referring to. `this.setState` should only be called from within a React component. Can you provide a code snippet and/or stack trace of the error? Thanks

**Comment by brianvoe** [comment]
I noticed the same thing. Has to do with es6 classes. You need to bind this to your class method, even when your class is extending React.Component. If your method is onChange() then in your constructor you would do this.onChange = this.onChange.bind(this);

**Comment by jakemmarsh** [comment]
Should be fixed in #24
