### ISSUE TITLE
Redux Branch

### ISSUE THREAD

**Issue by hoodsy** [jakemmarsh/react-rocket-boilerplate#22]
It would be great to see one of your awesome boilerplates with React+Redux!

**Comment by jakemmarsh** [comment]
This is definitely something I'd like to do at some point. I would also like to build one using Webpack/React Hot Loader, so these all could possibly warrant a separate boilerplate. I'll keep you updated!

**Comment by k00k** [comment]
:+1:

**Comment by jakemmarsh** [comment]
I've begun work on this here: https://github.com/jakemmarsh/react-booster-boilerplate

Still to-do: Redux and ImmutableJS logic, documentation
