### ISSUE TITLE
Not really an issue, Any forks with Flux instead of Reflux?

### ISSUE THREAD

**Issue by twoelevenjay** [jakemmarsh/react-rocket-boilerplate#25]
I thought I may be able to fork it and do this myself, but i keep breaking it, I am too much of a node noob lol.

Does anyone have any suggestions for this?

**Comment by jakemmarsh** [comment]
I've begun work on a Webpack/Redux version here: https://github.com/jakemmarsh/react-booster-boilerplate. It is still far from ready, though
