### ISSUE TITLE
npm install errors with node 5.0

### ISSUE THREAD

**Issue by varandpez** [jakemmarsh/react-rocket-boilerplate#30]
Using node 5.4.0 and npm 3.3.12 I have issues installing the dependencies.

npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global node-gyp@3.2.1 should be installed with -g
npm WARN prefer global bower@1.3.12 should be installed with -g

npm WARN EPEERINVALID react-router@1.0.3 requires a peer of history@^1.17.0 but none was installed

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.

Is there any node version that I should use to have successful install?

**Comment by nikbora** [comment]
Hey, history needs to be added as dependency with new react-router. For now you can fix it by running `npm install history --save` before `npm install`

**Comment by jakemmarsh** [comment]
If you were still having issues, 4dd6178c9af381c060777d641cb232e0153538ba may have fixed them. Try a fresh clone and `npm install`
