### ISSUE TITLE
Failed to parse SourceMap: http://localhost:3002/css/sass

### ISSUE THREAD

**Issue by Muntaner** [jakemmarsh/react-rocket-boilerplate#32]
I was using this boilerplate and was working very well.
From yesterday, all of a sudden, everytime I run "gulp dev" or "gulp prod", I get this error into my browser (in my chrome console): Failed to parse SourceMap: http://localhost:3002/css/sass.

React logic continues to work, but I have some style serious issues (for example, using Select from react-bootstrap package, the dropdown menu isn't working anymore).

This error also happens on an empty project, reproduced this way:
git clone https://github.com/jakemmarsh/react-rocket-boilerplate
cd in it
npm install
gulp dev

**Comment by Muntaner** [comment]
Update: the problem is present only when the project is in development mode "gulp dev". When I run "gulp prod" and serve the build/ folder via an HTTP server (tried with a Python SimpleHTTPServer) the problem isn't there.

**Comment by jakemmarsh** [comment]
This may have been solved by #33, could you get latest and provide an update?

**Comment by kalendubrick** [comment]
I've created a pull request ( #40 ) that fixes this issue.

**Comment by jakemmarsh** [comment]
Should be fixed in #40
