### ISSUE TITLE
question: additional npm libraries

### ISSUE THREAD

**Issue by paulocheque** [jakemmarsh/react-rocket-boilerplate#34]
I would like to include other js/css files inside my project. For example, bootstrap CSS and themes. But I would like to use a local file instead of a CDN.

What do you recommend with this gulp script? Include node_modules/**/*.css files in the build dir?

Or do you recommend any other config?

By the way, cool boilerplate!

**Comment by jakemmarsh** [comment]
Thanks for the support!

Personally, I would probably accomplish including third-party CSS by importing it within `app/styles/main.scss` (or some file downstream from that. That would just look something like this:

```scss
@import '../../node_modules/<path_to_file>.css';
```

The relative path can be a bit annoying, but this will include the external CSS in the SASS build process including minification, etc.

**Comment by paulocheque** [comment]
Great solution, thanks!
