### ISSUE TITLE
Using the API

### ISSUE THREAD

**Issue by rusjoan** [jakemmarsh/react-rocket-boilerplate#36]
Could you please show, how to use **login** action?
Interesting what the arguments passes to this method.

**Comment by jakemmarsh** [comment]
The API and associated actions are there merely as example files. This boilerplate does not come with an API. You should change [this line](https://github.com/jakemmarsh/react-rocket-boilerplate/blob/master/app/js/utils/APIUtils.js#L8) of APIUtils to point to wherever your own API is hosted. From there, it is up to you what actions to call and what parameters to pass to your API.
