### ISSUE TITLE
about api utils and back end

### ISSUE THREAD

**Issue by wuichen** [jakemmarsh/react-rocket-boilerplate#4]
im wondering how to use api utils? 
In the example, there's this line of code 
  root: '//localhost:3000/api/',

Should we route the api path in the server side? if so, how do i do it?

In the gulp file, I saw that all the routes are being directed to the client side to manipulate from this line of code 
  server.all('/*', function(req, res) {
      res.sendFile('index.html', { root: 'build' });
  });

**Comment by jakemmarsh** [comment]
In the gulp `server` file, it's just a small Express server purely for serving the `/build` directory. In the current configuration, this would not serve as your API. You would have to build out a separate server and eliminate/change the gulp server logic to serve an API alongside your application.

In `APIUtils.js`, the root is just the base URL of wherever your API is served. In the example URL, the API would be hosted at `localhost:3000/api`. You would have to update this to reflect your API's URL for any of the example HTTP logic to work.

**Comment by jakemmarsh** [comment]
Closing, as this isn't technically an issue
