### ISSUE TITLE
Router History Not working when deployed to hosting environment

### ISSUE THREAD

**Issue by nickfedoroff** [jakemmarsh/react-rocket-boilerplate#5]
When running in `gulp dev` mode, the router works fine. Refreshing a page like `mysite.com/mypage` works, as does going directly to that url. 

However, when I run `gulp prod` and deploy to my hosting environment, I get 404s from the server when refreshing child pages or trying to hit them directly. Is this an issue or do I need to do some kind of configuration to make history routing work properly on my host?

**Comment by jakemmarsh** [comment]
This is most likely an issue with your host/server. In `dev` mode, we're using an Express server that automatically routes anything besides static assets to the `build/index.html` file, allowing react-router to carry out all routing logic. I'm guessing your host is not configured this way, and so it's actually trying to find a `mypage` file in your root directory.

**Comment by nickfedoroff** [comment]
I was afraid of that. Thanks for the quick reply.
