### ISSUE TITLE
XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by tiagoj** [jakemmarsh/react-rocket-boilerplate#6]
The page opens up in the browser and shows something, but when I opened up the dev tools and checked for errors I found the following:

XMLHttpRequest cannot load http://localhost:3000/api/auth/check. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access.

**Comment by jakemmarsh** [comment]
See #2. This isn't an error with the boilerplate, it's just due to the boilerplate attempting to make an HTTP request to a non-existent endpoint.

**Comment by tiagoj** [comment]
Sorry I didn't catch the other issue.  Thanks for the quick comment.
