### ISSUE TITLE
unhandled nulls

### ISSUE THREAD

**Issue by tiagoj** [jakemmarsh/react-rocket-boilerplate#7]
After running gulp dev, the browser opens, change to localhost:3000 to see the direct version not proxied by browsersync.  Open the dev tools, and see the following error:

Uncaught TypeError: Cannot read property 'ok' of null       APIUtils.js:19

**Comment by jakemmarsh** [comment]
Strange. I believe since you were using `localhost:3000`, the API endpoint that your other issue talked about actually returned something (`index.html`), yet for some reason the `res` was null. Anyways, should be fixed in 618ead7f78c11715369caaf2648848bc75be5df7

**Comment by tiagoj** [comment]
Great, I just pulled it down and tested.  The error is gone.  Thanks again

**Comment by jakemmarsh** [comment]
:+1:
